services:
  app:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}:${IMAGE_TAG}
    container_name: project_app
    restart: unless-stopped
    env_file:
      - .env 
    networks:
      - project_network

  nginx:
    image: nginx:alpine
    container_name: project_nginx
    restart: unless-stopped
    ports:
      - "5001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - project_network

networks:
  project_network:
    driver: bridge